source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LCKit_Example', :exclusive => true do
  pod "LCKit", :path => "../"
end

target 'LCKit_Tests', :exclusive => true do
  pod "LCKit", :path => "../"

  pod 'FBSnapshotTestCase'
end
